"""
Canonical generic descriptions for hoverable chart elements.

Compact 1-sentence reference text per element. Plain string for now (v0.7);
v0.8 will add structured fields (glyph, canonical reference, line.color, etc.)
and a 'read deeper' link to LLM-generated placement-specific readings.

Total: 153 entries across 7 categories.
"""

PLANETS = {
    "sun":        {"name": "Sun",         "description": "Core identity, vitality, ego, the central organizing principle of the chart."},
    "moon":       {"name": "Moon",        "description": "Emotional nature, instincts, the inner world, subconscious patterns."},
    "mercury":    {"name": "Mercury",     "description": "Mind, communication, perception, learning style, how you process information."},
    "venus":      {"name": "Venus",       "description": "Love, beauty, attraction, values, what you find pleasurable."},
    "mars":       {"name": "Mars",        "description": "Drive, action, desire, anger, how you assert yourself."},
    "jupiter":    {"name": "Jupiter",     "description": "Expansion, philosophy, abundance, growth, faith, the principle of more."},
    "saturn":     {"name": "Saturn",      "description": "Structure, limits, discipline, time, where you must mature."},
    "uranus":     {"name": "Uranus",      "description": "Disruption, innovation, sudden change, individuation, awakening."},
    "neptune":    {"name": "Neptune",     "description": "Dreams, spirituality, illusion, dissolution, transcendence."},
    "pluto":      {"name": "Pluto",       "description": "Transformation, power, death/rebirth, the unconscious, deep change."},
    "north_node": {"name": "North Node",  "description": "Soul's growth direction, the path forward, future calling."},
    "south_node": {"name": "South Node",  "description": "Past patterns, comfort zone, what you came in already knowing."},
    "chiron":     {"name": "Chiron",      "description": "The wounded healer — the deepest wound that becomes the gift."},
}

SIGNS = {
    "Aries":       {"name": "Aries ♈",       "description": "Cardinal fire. Initiation, courage, raw will, beginnings."},
    "Taurus":      {"name": "Taurus ♉",      "description": "Fixed earth. Stability, sensuality, value, what endures."},
    "Gemini":      {"name": "Gemini ♊",      "description": "Mutable air. Curiosity, language, duality, mental quickness."},
    "Cancer":      {"name": "Cancer ♋",      "description": "Cardinal water. Emotional shelter, memory, family, the inner home."},
    "Leo":         {"name": "Leo ♌",         "description": "Fixed fire. Self-expression, creativity, the heart, sovereign play."},
    "Virgo":       {"name": "Virgo ♍",       "description": "Mutable earth. Refinement, service, discernment, craft."},
    "Libra":       {"name": "Libra ♎",       "description": "Cardinal air. Relationship, beauty, balance, the other."},
    "Scorpio":     {"name": "Scorpio ♏",     "description": "Fixed water. Depth, intimacy, transformation, the underworld."},
    "Sagittarius": {"name": "Sagittarius ♐", "description": "Mutable fire. Vision, philosophy, the quest, expansion."},
    "Capricorn":   {"name": "Capricorn ♑",   "description": "Cardinal earth. Authority, structure, mastery, the long arc."},
    "Aquarius":    {"name": "Aquarius ♒",    "description": "Fixed air. Vision for the collective, innovation, the outsider's gift."},
    "Pisces":      {"name": "Pisces ♓",      "description": "Mutable water. Dissolving boundaries, mysticism, compassion, dream."},
}

HOUSES = {
    "1":  {"name": "1st House — Self",        "description": "Body, appearance, the self you present, beginnings, the rising mask."},
    "2":  {"name": "2nd House — Resources",   "description": "Money, values, what you own, self-worth, the material body."},
    "3":  {"name": "3rd House — Mind",        "description": "Siblings, neighborhood, learning, daily communication, the immediate."},
    "4":  {"name": "4th House — Roots",       "description": "Home, family of origin, the inner foundation, what nourishes."},
    "5":  {"name": "5th House — Play",        "description": "Creativity, children, romance, what brings delight."},
    "6":  {"name": "6th House — Work",        "description": "Daily routine, health, service, the apprentice's craft."},
    "7":  {"name": "7th House — Other",       "description": "Partnerships, marriage, the projected mirror, open enemies."},
    "8":  {"name": "8th House — Depths",      "description": "Intimacy, shared resources, death, hidden things, the underworld."},
    "9":  {"name": "9th House — Horizons",    "description": "Travel, philosophy, higher learning, faith, the far country."},
    "10": {"name": "10th House — Calling",    "description": "Career, public reputation, what you're known for, the summit."},
    "11": {"name": "11th House — Network",    "description": "Friends, communities, hopes, the future held in common."},
    "12": {"name": "12th House — The Veil",   "description": "Solitude, dissolution, the unconscious, hidden gifts, retreat."},
}

ASPECTS = {
    "conjunction":  {"name": "Conjunction (0°)",     "description": "Two energies fused — intensified, blended, indistinguishable."},
    "opposition":   {"name": "Opposition (180°)",    "description": "Tension across an axis — two sides demanding integration."},
    "trine":        {"name": "Trine (120°)",         "description": "Harmonious flow — effortless cooperation between energies."},
    "square":       {"name": "Square (90°)",         "description": "Friction — growth through challenge, the catalyst aspect."},
    "sextile":      {"name": "Sextile (60°)",        "description": "Easy opportunity — flow that responds to small effort."},
    "quincunx":     {"name": "Quincunx (150°)",      "description": "Awkward angle — constant adjustment between unrelated signs."},
    "semi_sextile": {"name": "Semi-Sextile (30°)",   "description": "Minor irritation — signs side by side, learning to coexist."},
}

CENTERS = {
    "head":         {"name": "Head Center",         "description": "Pressure for inspiration; mental questions; the source of inquiry."},
    "ajna":         {"name": "Ajna Center",         "description": "Awareness; conceptualization; where ideas become structured thought."},
    "throat":       {"name": "Throat Center",       "description": "Manifestation; where everything becomes expression or action."},
    "g":            {"name": "G Center (Self)",     "description": "Identity, direction, love. The seat of the higher self."},
    "heart":        {"name": "Heart / Will Center", "description": "Ego, willpower, material world, promises kept."},
    "solar_plexus": {"name": "Solar Plexus",        "description": "Emotional awareness; the wave; deep moods; intimate truth."},
    "sacral":       {"name": "Sacral Center",       "description": "Life force; work; sexual energy; the gut response."},
    "spleen":       {"name": "Spleen Center",       "description": "Instinct; intuition; immune system; awareness in the present moment."},
    "root":         {"name": "Root Center",         "description": "Adrenal pressure; drive to act; stress that evolves you."},
}

GATES = {
     1: {"name": "Gate 1 — The Creative",                  "description": "Self-Expression. Knowing oneself as the source of creative force."},
     2: {"name": "Gate 2 — The Receptive",                 "description": "Direction of the Self. Knowing the way through receptivity."},
     3: {"name": "Gate 3 — Difficulty at the Beginning",   "description": "Ordering. Bringing form out of chaos through mutation."},
     4: {"name": "Gate 4 — Youthful Folly",                "description": "Formulization. Answering mental possibility with logic."},
     5: {"name": "Gate 5 — Waiting",                       "description": "Fixed Patterns. Universalization of natural rhythm and ritual."},
     6: {"name": "Gate 6 — Conflict",                      "description": "Friction. The intimacy of being in close emotional contact."},
     7: {"name": "Gate 7 — The Army",                      "description": "The Role of the Self in Interaction. The leader who guides."},
     8: {"name": "Gate 8 — Holding Together",              "description": "Contribution. Individual creative expression in service to the collective."},
     9: {"name": "Gate 9 — The Taming Power of the Small", "description": "Focus. Determining the detail that matters."},
    10: {"name": "Gate 10 — Treading",                     "description": "Behavior of the Self. Love of being yourself; self-love as action."},
    11: {"name": "Gate 11 — Peace",                        "description": "Ideas. The conceptualizer who holds ideas and shares them."},
    12: {"name": "Gate 12 — Standstill",                   "description": "Caution. The voice that speaks only when timing is right."},
    13: {"name": "Gate 13 — Fellowship of Man",            "description": "The Listener. Witness who holds the story for the future."},
    14: {"name": "Gate 14 — Possession in Great Measure",  "description": "Power Skills. Power expressed through capability and resources."},
    15: {"name": "Gate 15 — Modesty",                      "description": "Extremes. Living within the rhythm of natural extremes."},
    16: {"name": "Gate 16 — Enthusiasm",                   "description": "Skills. Mastery developed through experimentation and repetition."},
    17: {"name": "Gate 17 — Following",                    "description": "Opinions. The articulation of a logically-formed conclusion."},
    18: {"name": "Gate 18 — Work on What Has Been Spoiled","description": "Correction. The instinct to perfect and judge for improvement."},
    19: {"name": "Gate 19 — Approach",                     "description": "Wanting. The sensitivity to need; approaching for community and resource."},
    20: {"name": "Gate 20 — Contemplation",                "description": "The Now. Being present; the I AM that observes."},
    21: {"name": "Gate 21 — Biting Through",               "description": "The Hunter/Huntress. The need to control material domain."},
    22: {"name": "Gate 22 — Grace",                        "description": "Openness. Emotional grace; receptive to mood and meaning."},
    23: {"name": "Gate 23 — Splitting Apart",              "description": "Assimilation. Speaking insights at the right moment."},
    24: {"name": "Gate 24 — Return",                       "description": "Rationalization. Reviewing the past for fresh insight."},
    25: {"name": "Gate 25 — Innocence",                    "description": "The Spirit of the Self. Universal love; love without object."},
    26: {"name": "Gate 26 — The Taming Power of the Great","description": "The Egoist. Memory transformed into persuasive power."},
    27: {"name": "Gate 27 — Nourishment",                  "description": "Caring. The energy to care for and nourish others (or oneself)."},
    28: {"name": "Gate 28 — The Preponderance of the Great","description": "The Game Player. The struggle for meaning in the face of mortality."},
    29: {"name": "Gate 29 — The Abysmal",                  "description": "Saying Yes. Commitment to experience without knowing the outcome."},
    30: {"name": "Gate 30 — The Clinging Fire",            "description": "Feelings. The recognition of feelings as fate; desires as the engine."},
    31: {"name": "Gate 31 — Influence",                    "description": "Leading. Democratic leadership rooted in the now."},
    32: {"name": "Gate 32 — Duration",                     "description": "Continuity. Instinct for what endures across change."},
    33: {"name": "Gate 33 — Retreat",                      "description": "Privacy. Withdrawing to reflect; secrets held in trust."},
    34: {"name": "Gate 34 — The Power of the Great",       "description": "Power. Pure energetic power, available only to act."},
    35: {"name": "Gate 35 — Progress",                     "description": "Change. The thrill of new experience; the experimenter."},
    36: {"name": "Gate 36 — The Darkening of the Light",   "description": "Crisis. The emotional novice meeting first experiences."},
    37: {"name": "Gate 37 — The Family",                   "description": "Friendship. The community formed through agreement and bargain."},
    38: {"name": "Gate 38 — The Opposition",               "description": "The Fighter. The fight to find one's purpose."},
    39: {"name": "Gate 39 — Obstruction",                  "description": "The Provocateur. Provoking emotional clarity in others."},
    40: {"name": "Gate 40 — Deliverance",                  "description": "Aloneness. The will to be alone; the deliverer who refuses to carry the tribe."},
    41: {"name": "Gate 41 — Decrease",                     "description": "Contraction. Imagination born from limitation; the seed of feelings."},
    42: {"name": "Gate 42 — Increase",                     "description": "Growth. The maturation of experience through completion."},
    43: {"name": "Gate 43 — Breakthrough",                 "description": "Insight. The unique inner knowing that breaks through."},
    44: {"name": "Gate 44 — Coming to Meet",               "description": "Alertness. Pattern recognition; the salesperson; instinct for others."},
    45: {"name": "Gate 45 — Gathering Together",           "description": "The Gatherer. The voice of the king/queen; tribal leadership."},
    46: {"name": "Gate 46 — Pushing Upward",               "description": "Determination of the Self. Love of the body; embodied luck."},
    47: {"name": "Gate 47 — Oppression",                   "description": "Realization. Sudden clarity emerging from confusion."},
    48: {"name": "Gate 48 — The Well",                     "description": "Depth. The depth from which timely solutions emerge."},
    49: {"name": "Gate 49 — Revolution",                   "description": "Principles. Rejection (or acceptance) based on principle."},
    50: {"name": "Gate 50 — The Cauldron",                 "description": "Values. The keeper of tribal values and responsibility."},
    51: {"name": "Gate 51 — The Arousing",                 "description": "Shock. The competitor; awakening through shock and challenge."},
    52: {"name": "Gate 52 — Keeping Still",                "description": "Inaction. Stillness held as concentration; the mountain."},
    53: {"name": "Gate 53 — Development",                  "description": "Starting. The energy to begin new cycles."},
    54: {"name": "Gate 54 — The Marrying Maiden",          "description": "Ambition. The drive to be recognized and elevated."},
    55: {"name": "Gate 55 — Abundance",                    "description": "Spirit. Mood as fuel for spirit; abundance as feeling."},
    56: {"name": "Gate 56 — The Wanderer",                 "description": "Stimulation. The storyteller; sharing experience to provoke."},
    57: {"name": "Gate 57 — The Gentle",                   "description": "Intuition. Instinct in the now; the right ear; clarity."},
    58: {"name": "Gate 58 — The Joyous",                   "description": "Vitality. The aliveness of being challenged into perfection."},
    59: {"name": "Gate 59 — Dispersion",                   "description": "Sexuality. The drive to break through to intimacy."},
    60: {"name": "Gate 60 — Limitation",                   "description": "Acceptance. Accepting constraints as the doorway to mutation."},
    61: {"name": "Gate 61 — Inner Truth",                  "description": "Mystery. The pressure to know the unknowable."},
    62: {"name": "Gate 62 — Preponderance of the Small",   "description": "Detail. Articulation of facts; naming and ordering."},
    63: {"name": "Gate 63 — After Completion",             "description": "Doubt. The pressure of logical doubt that drives proof."},
    64: {"name": "Gate 64 — Before Completion",            "description": "Confusion. The pressure to make sense of what has happened."},
}

CHANNELS = {
    "1-8":   {"name": "Channel 1-8 — Inspiration",       "description": "The Creative Role Model. G ↔ Throat. Individual expression that inspires."},
    "2-14":  {"name": "Channel 2-14 — The Beat",         "description": "Keeper of Keys. G ↔ Sacral. Direction held by life-force resources."},
    "3-60":  {"name": "Channel 3-60 — Mutation",         "description": "Sacral ↔ Root. Energy that fluctuates and mutates through pulse."},
    "4-63":  {"name": "Channel 4-63 — Logic",            "description": "Ajna ↔ Head. Mental ease mixed with doubt; the logical formula."},
    "5-15":  {"name": "Channel 5-15 — Rhythm",           "description": "Sacral ↔ G. Being in the flow of natural rhythm."},
    "6-59":  {"name": "Channel 6-59 — Mating",           "description": "Solar Plexus ↔ Sacral. Reproduction in all its forms."},
    "7-31":  {"name": "Channel 7-31 — The Alpha",        "description": "G ↔ Throat. Democratic leadership for the future."},
    "9-52":  {"name": "Channel 9-52 — Concentration",    "description": "Sacral ↔ Root. Determined energetic focus."},
    "10-20": {"name": "Channel 10-20 — Awakening",       "description": "G ↔ Throat. Commitment to higher principles in the now."},
    "10-34": {"name": "Channel 10-34 — Exploration",     "description": "G ↔ Sacral. Following your convictions with full power."},
    "10-57": {"name": "Channel 10-57 — Perfected Form",  "description": "G ↔ Spleen. Survival of the self through intuition."},
    "11-56": {"name": "Channel 11-56 — Curiosity",       "description": "Ajna ↔ Throat. Searching for stimulation; the seeker."},
    "12-22": {"name": "Channel 12-22 — Openness",        "description": "Throat ↔ Solar Plexus. A social being moved by mood."},
    "13-33": {"name": "Channel 13-33 — The Prodigal",    "description": "G ↔ Throat. The witness of the past who returns home."},
    "16-48": {"name": "Channel 16-48 — The Wavelength",  "description": "Throat ↔ Spleen. Talent expressed through repetition and depth."},
    "17-62": {"name": "Channel 17-62 — Acceptance",      "description": "Ajna ↔ Throat. Organization through facts and detail."},
    "18-58": {"name": "Channel 18-58 — Judgment",        "description": "Spleen ↔ Root. Insatiability for the perfection of joy."},
    "19-49": {"name": "Channel 19-49 — Synthesis",       "description": "Root ↔ Solar Plexus. Sensitivity to community and resource."},
    "20-34": {"name": "Channel 20-34 — Charisma",        "description": "Throat ↔ Sacral. Where thought instantly becomes action."},
    "20-57": {"name": "Channel 20-57 — The Brainwave",   "description": "Throat ↔ Spleen. Penetrating awareness expressed."},
    "21-45": {"name": "Channel 21-45 — The Money Line",  "description": "Heart ↔ Throat. Materialist; control of domain."},
    "23-43": {"name": "Channel 23-43 — Structuring",     "description": "Throat ↔ Ajna. From inner knowing to outer expression."},
    "24-61": {"name": "Channel 24-61 — Awareness",       "description": "Ajna ↔ Head. The pressure of inner truth seeking thought."},
    "25-51": {"name": "Channel 25-51 — Initiation",      "description": "G ↔ Heart. The need to be first; the initiate."},
    "26-44": {"name": "Channel 26-44 — Surrender",       "description": "Heart ↔ Spleen. Faith and trust in instinct."},
    "27-50": {"name": "Channel 27-50 — Preservation",    "description": "Sacral ↔ Spleen. Custodianship of values and care."},
    "28-38": {"name": "Channel 28-38 — Struggle",        "description": "Spleen ↔ Root. The fighter who finds purpose through opposition."},
    "29-46": {"name": "Channel 29-46 — Discovery",       "description": "Sacral ↔ G. Sustained commitment in love and play."},
    "30-41": {"name": "Channel 30-41 — Recognition",     "description": "Solar Plexus ↔ Root. Focused energy of feelings and fantasy."},
    "32-54": {"name": "Channel 32-54 — Transformation",  "description": "Spleen ↔ Root. Driven ambition for material change."},
    "34-57": {"name": "Channel 34-57 — Power",           "description": "Sacral ↔ Spleen. Archetypal power serving instinct."},
    "35-36": {"name": "Channel 35-36 — Transitoriness",  "description": "Throat ↔ Solar Plexus. The need to change; new experience."},
    "37-40": {"name": "Channel 37-40 — Community",       "description": "Solar Plexus ↔ Heart. The bargain of family and tribe."},
    "39-55": {"name": "Channel 39-55 — Emoting",         "description": "Root ↔ Solar Plexus. Mood as fuel for spirit."},
    "42-53": {"name": "Channel 42-53 — Maturation",      "description": "Sacral ↔ Root. From beginning to completion; full cycles."},
    "47-64": {"name": "Channel 47-64 — Abstraction",     "description": "Ajna ↔ Head. Mental activity making sense of experience."},
}


MAYAN_DAY_SIGNS = {
    "Imox":     {"name": "Imox (Imix)",         "description": "Sea / primal water; dreamtime, the unconscious, the source."},
    "Iq'":      {"name": "Iq' (Ik)",            "description": "Wind / breath; spirit, communication, the moving force."},
    "Aq'ab'al": {"name": "Aq'ab'al (Akbal)",    "description": "Dawn / night-and-day; hidden potential, the inner journey."},
    "K'at":     {"name": "K'at (Kan)",          "description": "Net; capture, ensnarement, the binding of energies."},
    "Kan":      {"name": "Kan (Chicchan)",      "description": "Serpent; kundalini, body wisdom, transformation."},
    "Kame":     {"name": "Kame (Cimi)",         "description": "Death; surrender, the underworld, completion."},
    "Kej":      {"name": "Kej (Manik)",         "description": "Deer; divine grace, leadership, the four directions."},
    "Q'anil":   {"name": "Q'anil (Lamat)",      "description": "Star / rabbit; abundance, fertility, the seed."},
    "Toj":      {"name": "Toj (Muluc)",         "description": "Offering / payment; ritual, the price of life."},
    "Tz'i'":    {"name": "Tz'i' (Oc)",          "description": "Dog; law, justice, the loyal ancestor guide."},
    "B'atz'":   {"name": "B'atz' (Chuen)",      "description": "Monkey / weaver; artisan, creative time, the thread."},
    "E":        {"name": "E (Eb)",              "description": "Road; path, destiny, the journey of life."},
    "Aj":       {"name": "Aj (Ben)",            "description": "Reed; home, hearth, the masculine principle."},
    "I'x":      {"name": "I'x (Ix)",            "description": "Jaguar; shaman, magic, feminine power, earth wisdom."},
    "Tz'ikin":  {"name": "Tz'ikin (Men)",       "description": "Eagle; vision, freedom, the higher view, mediator."},
    "Ajmaq":    {"name": "Ajmaq (Cib)",         "description": "Warrior / ancestor; forgiveness, the lineage, the past."},
    "No'j":     {"name": "No'j (Caban)",        "description": "Wisdom / thought; the rational mind, earth movement."},
    "Tijax":    {"name": "Tijax (Etznab)",      "description": "Mirror / flint; truth-cutting, justice, sharpness."},
    "Kawoq":    {"name": "Kawoq (Cauac)",       "description": "Storm; healing, community, the gathering of forces."},
    "Ajpu":     {"name": "Ajpu (Ahau)",         "description": "Sun / hero; completion, the enlightened ancestor."},
}

MAYAN_TONES = {
    "1":  {"name": "Tone 1 — Hun (Unity)",          "description": "Beginnings, the source, undivided potential."},
    "2":  {"name": "Tone 2 — Ka (Duality)",         "description": "Polarity, partnership, the mirror that reveals."},
    "3":  {"name": "Tone 3 — Ox (Activation)",      "description": "Movement, communication, the spark."},
    "4":  {"name": "Tone 4 — Kan (Stability)",      "description": "Foundation, the four directions, structure."},
    "5":  {"name": "Tone 5 — Ho (Empowerment)",     "description": "Center, charisma, the radiant core."},
    "6":  {"name": "Tone 6 — Wak (Flow)",           "description": "Response, organic rhythm, the river."},
    "7":  {"name": "Tone 7 — Wuk (Reflection)",     "description": "Mystical center, the sacred mirror, depth."},
    "8":  {"name": "Tone 8 — Wajxak (Harmony)",     "description": "Balance, integration, the woven pattern."},
    "9":  {"name": "Tone 9 — Beleje (Patience)",    "description": "Expansion, the larger view, slow ripening."},
    "10": {"name": "Tone 10 — Lajuj (Manifestation)","description": "Completion, results, the apparent form."},
    "11": {"name": "Tone 11 — Junlajuj (Resolution)","description": "Simplification, release, letting go of what's done."},
    "12": {"name": "Tone 12 — Kab'lajuj (Understanding)","description": "Complexity, wisdom, the meta-view."},
    "13": {"name": "Tone 13 — Oxlajuj (Transcendence)","description": "Ascension, the open door, beyond form."},
}

CHINESE_ANIMALS = {
    "Rat":     {"name": "Rat 鼠",     "description": "Resourceful, charming, ambitious, socially adept."},
    "Ox":      {"name": "Ox 牛",      "description": "Diligent, dependable, strong, steady-handed."},
    "Tiger":   {"name": "Tiger 虎",   "description": "Brave, competitive, unpredictable, charismatic."},
    "Rabbit":  {"name": "Rabbit 兔",  "description": "Quiet, elegant, kind, responsible."},
    "Dragon":  {"name": "Dragon 龍",  "description": "Confident, intelligent, enthusiastic, powerful."},
    "Snake":   {"name": "Snake 蛇",   "description": "Enigmatic, intelligent, wise, intuitive."},
    "Horse":   {"name": "Horse 馬",   "description": "Animated, active, energetic, free-spirited."},
    "Goat":    {"name": "Goat 羊",    "description": "Calm, gentle, sympathetic, creative."},
    "Monkey":  {"name": "Monkey 猴",  "description": "Sharp, smart, curious, mischievous."},
    "Rooster": {"name": "Rooster 雞", "description": "Observant, hardworking, courageous, talented."},
    "Dog":     {"name": "Dog 狗",     "description": "Loyal, honest, prudent, kind-hearted."},
    "Pig":     {"name": "Pig 豬",     "description": "Compassionate, generous, diligent, easygoing."},
}

CHINESE_ELEMENTS = {
    "Wood":  {"name": "Wood",  "description": "Growth, vitality, generosity, idealism. Generates Fire."},
    "Fire":  {"name": "Fire",  "description": "Dynamism, passion, leadership, joy. Generates Earth."},
    "Earth": {"name": "Earth", "description": "Stability, nurturing, patience, reliability. Generates Metal."},
    "Metal": {"name": "Metal", "description": "Determination, structure, discipline, focus. Generates Water."},
    "Water": {"name": "Water", "description": "Wisdom, intuition, flexibility, depth. Generates Wood."},
}


def all_meanings() -> dict:
    """Return everything as a single JSON-serializable dict shaped for the viewer."""
    return {
        "planet": PLANETS,
        "sign": SIGNS,
        "house": HOUSES,
        "aspect": ASPECTS,
        "center": CENTERS,
        # Gate IDs are ints in source; JSON keys are strings, so convert.
        "gate":   {str(k): v for k, v in GATES.items()},
        "channel": CHANNELS,
        "mayan_day_sign": MAYAN_DAY_SIGNS,
        "mayan_tone": MAYAN_TONES,
        "chinese_animal": CHINESE_ANIMALS,
        "chinese_element": CHINESE_ELEMENTS,
    }
